export default goodList = [
    'Mirchi',
    'Chilli',
    'Cow Feed',
    'Fish Feed',
    'Fish',
    'Poultry Feed',
    'Book',
    'Cotton',
    'DOC',
    'Paper',
    'Wood',
    'Corrugated Boxes',
    'Machinery',
    'Metals',
    'Turmeric',
    'Spices',
    'Rice',
    'Construction Material',
    'Steel',
    'Cotton Oils',
    'Non-woven Fabrics',
    'News Print',
    'Cotton Hulls',
    'Cotton Bales',
    'Eggs',
    'Parcels',
    'Waste Paper',
    'Soap',
    'Textiles',
    'FMCG',
    'Cotton Yarn',
    'Engineering Parts',
    'Automotive Lubricants',
    'Plastic Household Items',
    'Plastic Pipes',
    'Metal Pipes/Tubes',
    'Chemical',
    'Jute',
    'Garments',
    'Wires',
    'Mechanical Parts',
    'Beverages',
    'Pesticides',
    'Edible Oil',
    'Cement',
    'Paper & Plastic Bags',
    'Rice Bran'
].sort();